import type { QuestionType } from '@/types/survey';

export const TYPE_TO_LABEL: Record<QuestionType, string> = {
  radiogroup: 'Radio Button Group',
  rating: 'Rating Scale',
  slider: 'Slider',
  checkbox: 'Checkboxes',
  dropdown: 'Dropdown',
  'dropdown-multi': 'Multi-Select Dropdown',
  boolean: 'Yes/No (Boolean)',
  file: 'File Upload',
  imagepicker: 'Image Picker',
  ranking: 'Ranking',
  text: 'Single-Line Input',
  comment: 'Long Text',
  multipletext: 'Multiple Textboxes',
  panel: 'Panel',
  paneldynamic: 'Dynamic Panel',
  matrix: 'Single-Select Matrix',
  matrixdropdown: 'Multi-Select Matrix',
  matrixdynamic: 'Dynamic Matrix',
  html: 'HTML',
  expression: 'Expression (read-only)',
  image: 'Image',
  signature: 'Signature',
};

export const LABEL_TO_TYPE: Record<string, QuestionType> = {
  'Radio Button Group': 'radiogroup',
  'Rating Scale': 'rating',
  Slider: 'slider',
  Checkboxes: 'checkbox',
  Dropdown: 'dropdown',
  'Multi-Select Dropdown': 'dropdown-multi',
  'Yes/No (Boolean)': 'boolean',
  'File Upload': 'file',
  'Image Picker': 'imagepicker',
  Ranking: 'ranking',
  'Single-Line Input': 'text',
  'Long Text': 'comment',
  'Multiple Textboxes': 'multipletext',
  Panel: 'panel',
  'Dynamic Panel': 'paneldynamic',
  'Single-Select Matrix': 'matrix',
  'Multi-Select Matrix': 'matrixdropdown',
  'Dynamic Matrix': 'matrixdynamic',
  HTML: 'html',
  'Expression (read-only)': 'expression',
  Image: 'image',
  Signature: 'signature',
};
